
  $('.list-group-item').click(function(){
    that=this;
    text=['This building  is inside of the new workplace. It has very excellent condition for users. Thera are so many equipments in the building.The gym, which will have almost 200 pieces of equipment and open training space, has been named "FITNESS CENTER".This pioneering new centre will provide unrivalled opportunities for everyone from beginner to elite athletes, supported by a world-class team of trainers and sports experts. It will be a home for our many sports clubs, allowing them to train and compete at the highest level.It will also have one of the most extensive and advanced centres in part to the quality and range of equipment, and supporting expertise. It will be an important centre for community health and well-being, and substantial effort has been made to ensure all facilities are as accessible as possible for those with disabilities, injuries or other specific access requirements.It features over 200 stations across two floors, and highly qualified staff whose mission it is to inspire you to discover how strong, how fast and how hard you can go. In addition to the state of the art equipment, this brand new gym has been designed to include open space where you can unleash yourself and undertake a whole body, functional workout.',
    'This is our new teacher. he teaches beginner course. He has many honours in this field. He has very valuable experience.He has these vital skills:Customer-service skills. Many fitness trainers and instructors must sell their services, motivating clients to hire them as personal trainers or to sign up for the classes they lead. Fitness trainers and instructors must therefore be polite, friendly, and encouraging to maintain relationships with their clients.Listening skills. To keep clients coming back for more classes or to continue personal training, fitness trainers and instructors must keep their clients motivated.Physical fitness. Fitness trainers and instructors need to be physically fit because their job requires a considerable amount of exercise. Group instructors often participate in classes, and personal trainers often need to show exercises to their clients.Problem-solving skills. Fitness trainers and instructors must evaluate each client’s level of fitness and create an appropriate fitness plan to meet the client’s individual needs.Speaking skills. Fitness trainers and instructors must be able to communicate well because they need to be able to explain exercises and movements to clients, as well as motivate them verbally during exercises.These skils is an essential for every trainers.therefore, we can prove you by showing these information.','This place is for boxing course. It has new equipment for the users. It has modern designed for the users.','Recently new equipments came to our workplace. It is great news for all people who are doing execasize','She is new woman teacher for intermediate and beginner in yoga and fitness course. She has great valuable experience in these field. She is 25 years old.','She is new woman teacher for intermediate years old.'
    ];
    
    $("#caption").html(text[$(that).data('slide-to')]);
   
  });

